# Generated by Django 5.0.1 on 2024-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_csvfileupload_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileupload',
            name='upload_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
